#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : pr                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/pr/app/lola-app/id1234793120 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://lola-app.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Lola App                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Lola app te acompañara todo el tiempo para mejorar tu calidad de vida. Lola te ayuda a hacer las cosas que te hacen falta para que te sientas mejor. Lola te ayuda a mantenerte motivado y a lograr tus metas. Lola te ayuda a ser más productivo y a alcanzar tus objetivos. Lola te ayuda a ser más feliz y a sentirte mejor.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Lola App                               
your_link                                 : https://lola-app.com                     
your_city                                 : Puerto Rico                                
email_address                             : contacto@lola-app.com
facebook_username                         :                                           
instagram_username                        : lola_app
twitter_username                          : lola_app
github_username                           :
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Recordatorios
    description                           : Lola guarda tus recordatorios en tu celular y te los muestra en tu teléfono.
    fontawesome_icon_name                 : calendar-alt
  
  - title                                 : Asistencia
    description                           : Preguntale a Lola inquetudes sobre tus metas y objetivos.
    fontawesome_icon_name                 : brain
  
  - title                                 : Seguimiento
    description                           : Lola te mostrará un resumen para que no olvides lo que tienes pendiente.
    fontawesome_icon_name                 : list-alt

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.175
topbar_title_color                        : "#ffffff"

# cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_image                               :                    # Replace with alternative image path or image URL.
# cover_overlay_color                       : "#363b3d"
cover_overlay_color                       : "#AB47BC"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#f2f2f2"

# link_color                                : "#1d63ea"
link_color                                : "#0d6efd"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

# extras
canonical_url                             : https://lola-app.com
og_image                                  : https://lola-app.com/assets/social-media-banner.png










####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
